{"date":"2016-12-08 19:32:42.477 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":54995495}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:33:19.102 +05:30",,"level":"Error","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: No such host is known ---> System.IO.IOException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 38","_errorId":"5f7796e6-d750-4470-bb29-1a35175adce6","_loggerId":43984699}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:33:19.151 +05:30",,"level":"Error","event":{"name":"SendEvents","facets":{"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: No such host is known ---> System.IO.IOException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 50\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Controllers.EventsController.<Post>d__3.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Controllers\\EventsController.cs:line 64","_errorId":"3330c562-c7d7-4bfd-8f2f-fb7b7a6d9814","_loggerId":54995495}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:35:31.120 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":54995495}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:38:46.297 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":30522299}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:40:44.155 +05:30",,"level":"Error","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 35","_errorId":"b1194744-1ee3-401e-80f1-080254d8e500","_loggerId":19650377}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:40:44.248 +05:30",,"level":"Error","event":{"name":"SendEvents","facets":{"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Controllers.EventsController.<Post>d__3.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Controllers\\EventsController.cs:line 64","_errorId":"0d51107e-2f23-4e4e-9c98-5c139a4359eb","_loggerId":30522299}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:40:47.425 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":30522299}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:41:29.598 +05:30",,"level":"Error","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 35","_errorId":"b7eca2c9-f0fa-4740-84d8-3f5d5c2249a7","_loggerId":19650377}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:41:29.826 +05:30",,"level":"Error","event":{"name":"SendEvents","facets":{"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.IO.IOException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 218.93.250.18:443\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Controllers.EventsController.<Post>d__3.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Controllers\\EventsController.cs:line 64","_errorId":"feb32590-527a-4d0e-913f-ff754203c253","_loggerId":30522299}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:43:32.643 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:44:32.041 +05:30",,"level":"Error","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: No such host is known ---> System.IO.IOException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 35","_errorId":"a4311f80-adb7-4c7c-bbb6-580c21d40533","_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:44:32.134 +05:30",,"level":"Error","event":{"name":"SendEvents","facets":{"_exception":"Microsoft.ServiceBus.Messaging.MessagingCommunicationException: An error occurred during communication with 'N/A'. Check the connection information, then retry. ---> System.ServiceModel.CommunicationException: No such host is known ---> System.IO.IOException: No such host is known ---> System.Net.Sockets.SocketException: No such host is known\r\n   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)\r\n   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.ConnectAsyncResult.<>c.<GetConnectTcpStep>b__23_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.ServiceBusClientWebSocket.EndConnect(IAsyncResult result)\r\n   at Microsoft.ServiceBus.WebSocketConnectAsyncResult.<GetAsyncSteps>b__13_1(WebSocketConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n\r\nServer stack trace: \r\n\r\n\r\nException rethrown at [0]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.Transport.WebSocketTransportInitiator.Complete(IAsyncResult connectAsyncResult, Boolean completeSynchronously)\r\n\r\nException rethrown at [1]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.ConnectAsyncResult.<>c.<GetAsyncSteps>b__13_3(ConnectAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [2]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.EndCreateConnection(IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.CreateAsyncResult.<>c.<GetAsyncSteps>b__5_1(CreateAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n\r\nException rethrown at [3]: \r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Common.AsyncResult`1.End(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.FaultTolerantObject`1.OnEndCreateInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)\r\n   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessagingFactory.OpenLinkAsyncResult.<>c.<GetAsyncSteps>b__35_3(OpenLinkAsyncResult thisPtr, IAsyncResult r)\r\n   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)\r\n   --- End of inner exception stack trace ---\r\n   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)\r\n   at Microsoft.ServiceBus.Messaging.MessageSender.EndSendEventData(IAsyncResult result)\r\n   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Processor.EventHubs.EventHubEventSender.<SendEventsAsync>d__2.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Processor\\EventHubEventSender.cs:line 47\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at DataBrain.Ingestion.Api.Controllers.EventsController.<Post>d__3.MoveNext() in D:\\GSI-CAT\\Code\\DataBrain\\Ingestion\\DataBrain.Ingestion.Api\\Controllers\\EventsController.cs:line 64","_errorId":"16e7c2a1-ce93-4225-99ce-9edbe24e6994","_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:45:59.353 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:46:06.175 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:47:05.860 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:47:07.964 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:00.263 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:08.055 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:13.241 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:13.732 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:14.990 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:55:15.478 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:00.326 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":2,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:00.784 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":2,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:03.311 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":2,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:03.689 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":2,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:04.740 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":2,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:05.081 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":2,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:06.067 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":2,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:06.407 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":2,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:07.312 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":2,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:07.659 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":2,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:17.652 +05:30",,"level":"Trace","event":{"name":"ParseEvents","facets":{"deviceId":"123","eventCount":24,"_loggerId":15369596}},"logger":"EventsController","environment":"dev","host":"MININT-UQJ6ACP"}
{"date":"2016-12-08 19:56:18.028 +05:30",,"level":"Trace","event":{"name":"SendEventsAsync","facets":{"deviceId":"123","batchCount":24,"_loggerId":60922235}},"logger":"EventHubEventSender","environment":"dev","host":"MININT-UQJ6ACP"}
